language: python

python:
  - 2.7
  - 3.6

sudo: false

install:
  # Install miniconda
  # -----------------
  - export CONDA_BASE=http://repo.continuum.io/miniconda/Miniconda
  - if [[ "$TRAVIS_PYTHON_VERSION" == 2* ]]; then
      wget ${CONDA_BASE}2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget ${CONDA_BASE}3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p ${HOME}/miniconda
  - export PATH="${HOME}/miniconda/bin:$PATH"

  # Create the testing environment
  # ------------------------------
  - conda config --set always_yes yes --set changeps1 no
  - conda config --set show_channel_urls True
  - conda config --add channels conda-forge
  - conda update --quiet conda
  - ENV_NAME='test-environment'
  - conda create --quiet -n ${ENV_NAME} python=${TRAVIS_PYTHON_VERSION} pip
  - source activate ${ENV_NAME}

  # Customise the testing environment 
  # ---------------------------------
  - conda install --quiet --file requirements.txt
  - pip install coveralls

  # Build the package
  # -----------------
  - python setup.py build_ext --inplace 

  # Output debug info
  # -----------------
  - conda list
  - conda info -a

script:
  - coverage run setup.py test


after_success: coveralls
